### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by NaLex248** [olegkapitonov/tubeAmp-Designer#6]
#include "kpp_tubeamp_dsp.h", No such file or directory for a src\processor.cpp file.

There is only a kpp_tubeamp.dsp file.

**Comment by olegkapitonov** [comment]
Hello, @NaLex248!

`faust` compiler should generate `kpp_tubeamp_dsp.h` header from `kpp_tubeamp.dsp`
at the beginning of the build process automatically.

Do you have `faust-2.x` compiler installed in your system?

Could you please post the output of `meson build` and `ninja -C build` commands?

**Comment by NaLex248** [comment]
I didn't know it worked like that. I've tried building this on Windows. All is clear, thank you!
